apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-application
  labels:
    app: api-application
spec:
  selector:
    matchLabels:
      app: api-application
  replicas: 1
  template:
    metadata:
      labels:
        app: api-application
    spec:
      containers:
        - name: api-application
          image: "jeversontp/api-application:v3"
          envFrom:
            - configMapRef:
                name: api-application-env
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"