apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  labels:
    app: processor
spec:
  selector:
    matchLabels:
      app: processor
  replicas: 3
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
        - name: processor
          image: "jeversontp/processor:v2"
          envFrom:
            - configMapRef:
                name: processor-env
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"